services:
  - type: web
    name: chat-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run dev
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
